name: Baixar RPE 2024

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Playwright + Dependencies
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Run download script
        run: python download.py

      - name: Upload ZIPs
        uses: actions/upload-artifact@v4
        with:
          name: RPE_2024_ZIPs
          path: "*.zip"